/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/amr_cmd.h
  Source: /home/songguoqing/sim2real/idl/amr_cmd.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_AMR_CMD_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_AMR_CMD_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum dobot_atom_msg_dds__AMRCommandType
{
  dobot_atom_msg_dds__CANCEL_TASK,
  dobot_atom_msg_dds__PAUSE_TASK,
  dobot_atom_msg_dds__RESUME_TASK,
  dobot_atom_msg_dds__MOVE_TO_TAG,
  dobot_atom_msg_dds__REMOTE_CONTROL,
  dobot_atom_msg_dds__ROTATE,
  dobot_atom_msg_dds__START_REMOTE,
  dobot_atom_msg_dds__STOP_REMOTE,
  dobot_atom_msg_dds__SUBSCRIBE_LASER,
  dobot_atom_msg_dds__UNSUBSCRIBE_LASER,
  dobot_atom_msg_dds__START_MAPPING,
  dobot_atom_msg_dds__SAVE_MAP,
  dobot_atom_msg_dds__STOP_MAPPING,
  dobot_atom_msg_dds__SET_VEL,
  dobot_atom_msg_dds__SET_ACCEL,
  dobot_atom_msg_dds__SET_DECEL
} dobot_atom_msg_dds__AMRCommandType;

#define dobot_atom_msg_dds__AMRCommandType__alloc() \
((dobot_atom_msg_dds__AMRCommandType*) dds_alloc (sizeof (dobot_atom_msg_dds__AMRCommandType)));

typedef struct dobot_atom_msg_dds__AMRCommand_
{
  dobot_atom_msg_dds__AMRCommandType command_type;
  uint32_t target_id;
  float linear_vel;
  float angular_vel;
  uint32_t command_id;
  uint64_t timestamp;
  float theta;
} dobot_atom_msg_dds__AMRCommand_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__AMRCommand__desc;

#define dobot_atom_msg_dds__AMRCommand___alloc() \
((dobot_atom_msg_dds__AMRCommand_*) dds_alloc (sizeof (dobot_atom_msg_dds__AMRCommand_)));

#define dobot_atom_msg_dds__AMRCommand__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__AMRCommand__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_AMR_CMD_H */
