/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/amr_state.h
  Source: /home/songguoqing/sim2real/idl/amr_state.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_AMR_STATE_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_AMR_STATE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum dobot_atom_msg_dds__NavigationStatus_
{
  dobot_atom_msg_dds__UNKNOWN,
  dobot_atom_msg_dds__QUEUING,
  dobot_atom_msg_dds__RUNNING,
  dobot_atom_msg_dds__COMPLETED,
  dobot_atom_msg_dds__FAILED,
  dobot_atom_msg_dds__PAUSED,
  dobot_atom_msg_dds__CANCELED,
  dobot_atom_msg_dds__WAITING_CONFIRM,
  dobot_atom_msg_dds__IDLE,
  dobot_atom_msg_dds__STOPPED
} dobot_atom_msg_dds__NavigationStatus_;

#define dobot_atom_msg_dds__NavigationStatus___alloc() \
((dobot_atom_msg_dds__NavigationStatus_*) dds_alloc (sizeof (dobot_atom_msg_dds__NavigationStatus_)));

typedef enum dobot_atom_msg_dds__DeviceStatus_
{
  dobot_atom_msg_dds__DEVUNKNOWN,
  dobot_atom_msg_dds__DEVIDLE,
  dobot_atom_msg_dds__TASKING,
  dobot_atom_msg_dds__ERROR,
  dobot_atom_msg_dds__OFFLINE,
  dobot_atom_msg_dds__INIT,
  dobot_atom_msg_dds__CHARGING,
  dobot_atom_msg_dds__UPGRADE
} dobot_atom_msg_dds__DeviceStatus_;

#define dobot_atom_msg_dds__DeviceStatus___alloc() \
((dobot_atom_msg_dds__DeviceStatus_*) dds_alloc (sizeof (dobot_atom_msg_dds__DeviceStatus_)));

typedef struct dobot_atom_msg_dds__AMREventStatus_
{
  bool emergency_stop_pressed;
  bool enable_pressed;
  bool path_blocked;
  bool low_battery;
  bool obstacle_detected;
} dobot_atom_msg_dds__AMREventStatus_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__AMREventStatus__desc;

#define dobot_atom_msg_dds__AMREventStatus___alloc() \
((dobot_atom_msg_dds__AMREventStatus_*) dds_alloc (sizeof (dobot_atom_msg_dds__AMREventStatus_)));

#define dobot_atom_msg_dds__AMREventStatus__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__AMREventStatus__desc, (o))

typedef struct dobot_atom_msg_dds__AMRBasicStatus_
{
  float battery_level;
  float battery_voltage;
  float battery_current;
  uint16_t heartbeat;
} dobot_atom_msg_dds__AMRBasicStatus_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__AMRBasicStatus__desc;

#define dobot_atom_msg_dds__AMRBasicStatus___alloc() \
((dobot_atom_msg_dds__AMRBasicStatus_*) dds_alloc (sizeof (dobot_atom_msg_dds__AMRBasicStatus_)));

#define dobot_atom_msg_dds__AMRBasicStatus__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__AMRBasicStatus__desc, (o))

typedef struct dobot_atom_msg_dds__AMRState_
{
  dobot_atom_msg_dds__DeviceStatus_ device_status;
  dobot_atom_msg_dds__NavigationStatus_ navigation_status;
  struct dobot_atom_msg_dds__AMRBasicStatus_ basic_status;
  float position[3];
  struct dobot_atom_msg_dds__AMREventStatus_ amr_event;
  uint32_t error_code[32];
  uint32_t task_id;
  uint32_t work_mode;
} dobot_atom_msg_dds__AMRState_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__AMRState__desc;

#define dobot_atom_msg_dds__AMRState___alloc() \
((dobot_atom_msg_dds__AMRState_*) dds_alloc (sizeof (dobot_atom_msg_dds__AMRState_)));

#define dobot_atom_msg_dds__AMRState__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__AMRState__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_AMR_STATE_H */
