/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/emergency_state.h
  Source: /home/songguoqing/sim2real/idl/emergency_state.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_EMERGENCY_STATE_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_EMERGENCY_STATE_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__EmergencyState_
{
  bool soft_emergency_triggered;
  bool hard_emergency_triggered;
  bool amr_emergency_triggered;
  bool di_emergency_triggered;
} dobot_atom_msg_dds__EmergencyState_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__EmergencyState__desc;

#define dobot_atom_msg_dds__EmergencyState___alloc() \
((dobot_atom_msg_dds__EmergencyState_*) dds_alloc (sizeof (dobot_atom_msg_dds__EmergencyState_)));

#define dobot_atom_msg_dds__EmergencyState__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__EmergencyState__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_EMERGENCY_STATE_H */
