/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/enable_motors.h
  Source: /home/songguoqing/sim2real/idl/enable_motors.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_ENABLE_MOTORS_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_ENABLE_MOTORS_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__EnableMotors_
{
  bool flag[29];
} dobot_atom_msg_dds__EnableMotors_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__EnableMotors__desc;

#define dobot_atom_msg_dds__EnableMotors___alloc() \
((dobot_atom_msg_dds__EnableMotors_*) dds_alloc (sizeof (dobot_atom_msg_dds__EnableMotors_)));

#define dobot_atom_msg_dds__EnableMotors__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__EnableMotors__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_ENABLE_MOTORS_H */
