/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /home/songguoqing/sim2real/build/generated_dds/remote_control.h
  Source: /home/songguoqing/sim2real/idl/remote_control.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_REMOTE_CONTROL_H
#define DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_REMOTE_CONTROL_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dobot_atom_msg_dds__JoystickValue_
{
  float x;
  float y;
} dobot_atom_msg_dds__JoystickValue_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__JoystickValue__desc;

#define dobot_atom_msg_dds__JoystickValue___alloc() \
((dobot_atom_msg_dds__JoystickValue_*) dds_alloc (sizeof (dobot_atom_msg_dds__JoystickValue_)));

#define dobot_atom_msg_dds__JoystickValue__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__JoystickValue__desc, (o))

typedef struct dobot_atom_msg_dds__RemoteControl_
{
  struct dobot_atom_msg_dds__JoystickValue_ btn_move;
  struct dobot_atom_msg_dds__JoystickValue_ btn_turn;
} dobot_atom_msg_dds__RemoteControl_;

extern const dds_topic_descriptor_t dobot_atom_msg_dds__RemoteControl__desc;

#define dobot_atom_msg_dds__RemoteControl___alloc() \
((dobot_atom_msg_dds__RemoteControl_*) dds_alloc (sizeof (dobot_atom_msg_dds__RemoteControl_)));

#define dobot_atom_msg_dds__RemoteControl__free(d,o) \
dds_sample_free ((d), &dobot_atom_msg_dds__RemoteControl__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__HOME_SONGGUOQING_SIM2REAL_BUILD_GENERATED_DDS_REMOTE_CONTROL_H */
